const data = {
  "login": "prateekj480",
  "id": 72737546,
  "node_id": "MDQ6VXNlcjcyNzM3NTQ2",
  "avatar_url": "https://avatars.githubusercontent.com/u/72737546?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/prateekj480",
  "html_url": "https://github.com/prateekj480",
  "followers_url": "https://api.github.com/users/prateekj480/followers",
  "following_url": "https://api.github.com/users/prateekj480/following{/other_user}",
  "gists_url": "https://api.github.com/users/prateekj480/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/prateekj480/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/prateekj480/subscriptions",
  "organizations_url": "https://api.github.com/users/prateekj480/orgs",
  "repos_url": "https://api.github.com/users/prateekj480/repos",
  "events_url": "https://api.github.com/users/prateekj480/events{/privacy}",
  "received_events_url": "https://api.github.com/users/prateekj480/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Prateek Jain",
  "company": null,
  "blog": "",
  "location": "Beawar, Rajasthan, India",
  "email": null,
  "hireable": true,
  "bio": "I'm a Javascript enthusiast looking to learn all things Javascript. I hope to land a job as a full stack developer",
  "twitter_username": null,
  "public_repos": 9,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2020-10-12T10:04:21Z",
  "updated_at": "2021-03-14T14:40:14Z"
}

export default JSON.parse(JSON.stringify(data))